### PR TITLE
Config web port

### PR DESCRIPTION
**Pull request by MatteoPierro**

### CODE REVIEW

**Comment by MatteoPierro** [comment]
@christian-fei can you review please? ;)

**Comment by christian-fei** [comment]
:+1: , although I'm not madly in love with the change in the worker.
if not a property of the worker, at least a var for the http_port https://github.com/MatteoPierro/elixir-plug-api-example/blob/config-web-port/lib/api/worker.ex

PS: in config.exs you left the `http_port` untouched, instead of renaming it to `port` as in the other config files :)

**Comment by MatteoPierro** [comment]
I agree with you, I have extracted a variable for the http_port

**Comment by pdincau** [comment]
merged

**Pull request merged**
